version: "3"
services:
  client:
    build: ./client
    volumes:
    - ./client:/code
    # - /code/node_modules
    ports:
    - "3000:3000"
  server:
    build: ./server
    volumes:
    - ./server:/code
    # - /code/node_modules
    ports:
    - "3001:3001"
    environment:
      PGUSER: cfc
      PGPASSWORD: apple1
      PGHOST: db
      PGPORT: 5432
      PORT: 3001
    links:
    - db
    - test_db
  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: apple1
      POSTGRES_USER: cfc
  test_db:
    build: ./test_db
    environment:
      POSTGRES_PASSWORD: apple1
      POSTGRES_USER: cfc